type USDT0Transfer {
  id: ID! # use guid
  srcChain: Int!
  dstChain: Int!
  fromAddress: String!
  toAddress: String!
  amountSent: Float!
  amountReceived: Float!
  txHashSent: String!
  txHashReceived: String!
}

# lets call this chain as primary
type DailyUSDT0TransferStats {
  id: ID! # chainId-unixTimestamp
  date: Int! # unix timestamp at 00:00 UTC
  totalSentTransfers: Int!
  totalReceivedTransfers: Int!
  totalAmountSent: Float!
  totalAmountReceived: Float!
  # statsByChain: [StatsByChain!]!
}

type StatsByChain {
  id: ID! # primary-secondary-timestamp
  chainId: Int!
  sentCount: Int!
  amountSent: Float!
  receivecCount: Int!
  amountReceived: Float!
}

